### ISSUE TITLE
Inferred version (0.1.0-dev.1) must have higher precedence than previous (1.0.0-SNAPSHOT)

### ISSUE THREAD

**Issue by lguminski** [ajoberstar/reckon#14]
I would like to use `semver-vcs-gradle-grgit` to implement semantic versioning in a way that entire versioning process bases on git tags (read from GitHub). Something of this sort

```
$ git tag
0.1.0
$ gradle properties | grep version
version: 0.1.1.dev.1
$ gradle release -Prelease.scope=minor -Prelease.stage=final
...
$ git tag
0.1.0
0.2.0
$ gradle properties | grep version
version: 0.2.1.dev.1
```

With a snippets of code that I wrote, I am facing

```
Inferred version (0.1.0-dev.1) must have higher precedence than previous (1.0.0-SNAPSHOT)
```

but I am not even sure if the direction is correct. Some guidance is highly welcomed. This is a snipped of groovy:

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.ajoberstar:semver-vcs-gradle-grgit:0.1.0-milestone.1"
    classpath "org.ajoberstar:grgit:1.3.0"
  }
}

apply plugin: 'org.ajoberstar.release-opinion'
apply plugin: 'org.ajoberstar.semver-vcs-grgit'

import org.ajoberstar.grgit.Grgit
import org.ajoberstar.gradle.git.release.opinion.Strategies

release {
  grgit = Grgit.open(project.file('.'))
  versionStrategy Strategies.FINAL
  def strategy = Strategies.SNAPSHOT
  strategy = strategy.copyWith(createTag: true)
  defaultVersionStrategy = strategy
  tagStrategy {
    prefixNameWithV = false // defaults to true
    generateMessage = { version -> "Released by $user" }
  }
```

**Comment by ajoberstar** [comment]
First disclaimer is that mixing the `gradle-git` release plugin and the `semver-vcs` plugins isn't really supported right now. I'm not sure exactly how that would work out right now, but I plan to support this eventually.

By default, the strategies in `release-opinion` enforce version precedence, which is why you are getting a failure right now. You either need to disable the enforcePrecedence setting on your strategies or just plan to always use a higher version. Also tagging SNAPSHOTs doesn't seem like a good idea, since they're not unique.

Let me know if you have more questions.

**Comment by lguminski** [comment]
Ok. I will implement this in some other way. Thank you for the answer.
