### ISSUE TITLE
[Question]  Increment further when +-rc.* version on different branch

### ISSUE THREAD

**Issue by mathiasmaerker** [ajoberstar/reckon#59]
Hi there,
sorry if I ask this question, I am rather new to SemVer, so maybe Stackoverflow would be a better place to ask, but because I am evaluation this plugin, I hope you don't mind the question.

Assuming I have a current version of
0.2.0-rc.1 in branch release/0.2.0 

and wile this release is prepared, which may take some time for testing etc. an other Team should work on next feature iterations but here it seems to me that this is not possible because until I have a final version(0.2.0) only the -rc.* versions are incremented  and maybe I am developing new features which should result in 0.3.0-milestone even while 0.2.0-rc.* isn't released.

Or am I just totally not understanding SemVer and the whole process?

Kind regards
Mathias

**Comment by ajoberstar** [comment]
Yes the approach you're talking about should work (both for SemVer in general and reckon).

Rough scenario of what I think you're describing (which should work in this plugin):

- 0.1.0 is tagged somewhere on master (and was your first release)
- A 0.2.0 branch is created and you tag/release 0.2.0-rc.1
- Development continues on master (reckon considers this 0.3.0-*, since 0.2.0 is "claimed" by the other branch)
- Release prep continues on 0.2.0 branch and you can release more rcs and get to the final version.

Let me know if you have further questions.

**Comment by mathiasmaerker** [comment]
I just tested it, seems fine to me. Thank you so much for your time and effort
Regards
Mathias
