### ISSUE TITLE
Configuring remote to enable reckonTagPush task from a fork

### ISSUE THREAD

**Issue by rohanliston** [ajoberstar/reckon#89]
Is it possible to configure which remote `reckonTagPush` pushes tags to?

Context:
At my workplace, all developers create their own fork of the main repository for a given project and submit pull requests back to the main repository (remote `upstream`) from their fork (remote `origin`).

`reckonTagPush` pushes tags to `origin`, which means that developers responsible for releasing versions via tags would have to have a second checkout with `origin` pointing to the main repository rather than just doing the equivalent of `git push upstream <tagname>`.

**Comment by ajoberstar** [comment]
Currently, this isn't configurable. It pushes to whatever remote your current branch is tracking. This could probably enhanced, though I'd probably be looking for someone to contribute this one, since it won't be high on my list.

As a workaround, you can run `reckonTagCreate` then do the `git push upstream <tagname>`.

**Comment by lehn-etracker** [comment]
+1

**Comment by EarthCitizen** [comment]
Having a configurable remote is not only useful for forks. Bamboo clones repos into a cache copy, then when your project builds, it gets cloned from Bamboo's cache copy instead of the remote server. As a result, if you push your release to origin, it only pushes to Bamboo's cache clone and never makes it to the remote server. The only way around this is to add a new remote and push the release to that remote. So, being unable to configure the remote to push to makes it impossible to use this plugin with Bamboo, if I am correctly understanding the limitations of reckon.
