### ISSUE TITLE
Proposal - add a timestamp to metadata of "uncommitted" versions

### ISSUE THREAD

**Issue by s4nk** [ajoberstar/reckon#90]
Use case:
During development cycle I keep experimenting, re-building and re-running my service. I would like the created artifacts (Docker images in my case) to have unique versions, but without commiting every change. 

Proposed solution:
Add an ISO 8601 timestamp to version metadata when repository is dirty in
https://github.com/ajoberstar/reckon/blob/0f980deadcc7901e4c42b10569928a976e7bfaa1/reckon-core/src/main/java/org/ajoberstar/reckon/core/Reckoner.java#L122
, e.g.:
`0.1.0-beta.0.1+e06c68a863eb6ceaf889ee5802f478c10c1464bb.uncommitted.20180615T084953Z`

It's fairly simple to implement, I can open a PR if you think it makes sense.

**Comment by s4nk** [comment]
Alternatively the "uncommitted" suffix could become a timestamp instead.

**Comment by ajoberstar** [comment]
Seems worth considering. #86 is going to change the build metadata a little anyway, could change this at the same time.

Part of the deal with that one was to keep the metadata short though. I could see a couple options for this:

1. `0.1.0-beta.0.1+e06c68a863eb6ceaf889ee5802f478c10c1464bb.uncommitted.20180615T084953Z`
1. `0.1.0-beta.0.1+e06c68a863eb6ceaf889ee5802f478c10c1464bb.20180615T084953Z`
1. `0.1.0-beta.0.1+uncommitted.20180615T084953Z`
1. `0.1.0-beta.0.1+20180615T084953Z`
1. `0.1.0-beta.0.1+uncommitted.1529052593` (use epoch seconds instead of ISO for brevity)

I like dropping the commit hash, since you're in an uncommitted state anyway.

However, this would also have to consider how Gradle sorts versions, which might mean we have to keep the hash.

**Comment by s4nk** [comment]
That's great, thanks!
